### ISSUE TITLE
Skipping ~/jetson-files if it only contains the zip image

### ISSUE THREAD

**Issue by cvaisnor** [cranky-cyborg/Jetson-Flash-Manager#3]
Awesome script!! I got this to work yesterday but had to tweak a few things. 

For the ~/jetson-files dir, I had placed the Deepstream .deb as well as my Jetson image in compressed zip format. 

It looks like the if-statements in flashmgr.sh at https://github.com/cranky-cyborg/Jetson-Flash-Manager/blob/c7ae7d0fbf80fdf691591a3a6de9b637dd4a9d8f/flashmgr.sh#L91 and at https://github.com/cranky-cyborg/Jetson-Flash-Manager/blob/c7ae7d0fbf80fdf691591a3a6de9b637dd4a9d8f/flashmgr.sh#L96 should be swapped.

Because I had never unzipped the image file, the statement at L#91 skips at checking the rest of the dir.

**Comment by cranky-cyborg** [comment]
The logic behind that is simple.

If (the blob.img file is extracted and is ready to use ) then
    flash the image
else if ( the zip file is available) then
   unzip the file, and flash the image.
end if

noting in both cases, the script checks the MD5 hash so jumping straight to blob.img will save a few minutes if the script has been executed before or the file exists.

hope this makes sense.
